language: java
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  app:
    main: warm-wildwood-55906
  api_key:
    secure: IuwZRpn+6pFbIVQZi7Ofr8+Z7ZFomkIWGoOy2ZGg3BJeV8T3FWAcsnTAJHQzxcY31WXLDSULPHPTI2QSYhETzOOw9PLL1v6KfBj0MOmBh+NwO0KtEH5M5eI4SdwgzBW780jR0oP0Cgd2OGYL/QG3+73232OwmtV0Y1rY/bRuJsR0lxNlffKt8wAwR7zeKkSbY8YImtzZv7wdvcBklcf2Fqv6dtmG2FWI7TXmQv/kXuDQPojcdUTbKhwieR81qpjP13MuUFjIj4jrB4fFQLNfVcT4ja81iwXbQEaE2W8/0SpDMQwHvMVZSUog5+9Nk1cCihduEZhekgqFDJsOfyGPJOvYBHTW9Gf9BYZrdyz4mqkpoNqLnMTB32uwQ+8L/q/0A9cPEeMquF5+QqJStRm6lrRE3TaX/ZM78U8kjIo66bDobSpqpzgVIJZxG2qEjhzj+rG7lx0+tQEtZRvrWeFN9qpsRXT0xBKDVxQfwEIM8n8EuFB9iiZdGvFUtb2XjtLlzxtJnDR2HqILUW+61Yhm6JRAuXSzjLseoG/mxwj3py2DwPl0EUbtKRIdCw9KRVUgrjUbjW404CIpO621UDhvBbZ8nQ2/KO0Nv0uDIKZKFYfZlorQlchLXTp6k1fBzYzgmR9ig4g/JBIDrlVIR8S9WnBWcbkbIubotE/bYK6HhhE=
